// ============================================================
//  studio/image.js — destination photos generated by Gemini
//  Own prompt (Carousel's generator stays untouched): natural,
//  documentary-style travel photography, and the client's hard rule:
//  no religious buildings or symbols of any kind.
// ============================================================

const config = require('../config');

const VARIANTS = [
  'a quiet seaside or riverside promenade in the late afternoon',
  'a characteristic old-town street with cafés, seen at eye level',
  'a wide landscape view of the coast, hills or water around the city',
  'a modern skyline or bridge at blue hour',
  'a local market or harbour scene with soft natural light',
];

function buildPrompt(city, variant) {
  return [
    `A real, unedited travel photograph of ${city}: ${variant}.`,
    'Shot by a professional travel photographer on a full-frame camera with a 35mm lens, natural daylight,',
    'true-to-life colours, gentle contrast, realistic textures and slight natural imperfections.',
    'It must look like an authentic photo, not a rendering: no HDR look, no oversaturation, no glow, no fantasy sky.',
    'Absolutely NO mosques, minarets, domes, churches, cathedrals, temples, crosses, crescents or any religious building or symbol anywhere in the frame.',
    'No people in close-up, no text, no logos, no watermarks. Keep the upper 12% of the frame calm (sky) for a logo.',
    'Vertical 9:16 composition, main subject in the middle band.',
  ].join(' ');
}

/** Returns a data URI (image) or throws. */
async function generatePhoto(city) {
  if (!config.GEMINI_API_KEY) throw new Error('GEMINI_API_KEY is not set');
  const variant = VARIANTS[Math.floor(Math.random() * VARIANTS.length)];
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${config.GEMINI_IMAGE_MODEL}:generateContent`;
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-goog-api-key': config.GEMINI_API_KEY },
    body: JSON.stringify({
      contents: [{ parts: [{ text: buildPrompt(city, variant) }] }],
      generationConfig: { responseModalities: ['Image'], imageConfig: { imageSize: config.GEMINI_IMAGE_SIZE || '2K', aspectRatio: '9:16' } },
    }),
    signal: AbortSignal.timeout(120000),
  });
  if (!res.ok) throw new Error(`Gemini image error ${res.status}`);
  const json = await res.json();
  const part = (json?.candidates?.[0]?.content?.parts || []).find((p) => p.inlineData || p.inline_data);
  if (!part) throw new Error('Gemini returned no image');
  const inline = part.inlineData || part.inline_data;
  return `data:${inline.mimeType || inline.mime_type || 'image/png'};base64,${inline.data}`;
}

module.exports = { generatePhoto, buildPrompt };
